name: node-sample-app

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

  backend:
    build: '.'
    depends_on:
      - db
      - minio
    volumes:
      - ./src:/app/src
    restart: always
    environment:
      PORT: 3001
    env_file: '.env'

  client:
    image: public.ecr.aws/r5p6q2u1/js-example-spa:v1.0.2
    depends_on:
      - backend
    restart: always
    environment:
      PORT: 3000

  gateway:
    image: nginx:alpine
    depends_on:
      - db
      - client
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 3000:80
    environment:
      - CLIENT_PORT=3000
      - BACKEND_PORT=3001

volumes:
  pgdata:
  miniodata:
