apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o helm
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/node-sample-app-default: 'true'
        io.kompose.service: backend
    spec:
      containers:
        - image: public.ecr.aws/r5p6q2u1/node-sample-app-backend:{{ .Chart.AppVersion }}
          name: backend
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always
