{{- if .Values.s3.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: empty-s3-bucket
  annotations:
    "helm.sh/hook": pre-delete # This job will be triggered during helm uninstall/delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli:2.17.13
        command: ["sh", "-c", "aws s3 rm s3://{{ .Values.s3.bucket }} --recursive --region {{ .Values.s3.region }}"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cloud-provider-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-provider-secret
              key: aws_secret_access_key
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
