apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o helm
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/node-sample-app-default: 'true'
        io.kompose.service: worker
    spec:
      containers:
        - image: public.ecr.aws/r5p6q2u1/node-sample-app-worker:{{ .Chart.AppVersion }}
          name: worker
      restartPolicy: Always
